name = "NonconvexBayesian"
uuid = "fb352abc-de7b-48de-9ebd-665b54b5d9b3"
authors = ["Mohamed Tarek <mohdibntarek@gmail.com> and contributors"]
version = "0.2.0"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
NonconvexIpopt = "bf347577-a06d-49ad-a669-8c0e005493b8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[compat]
AbstractGPs = "0.3, 0.4, 0.5"
ChainRulesCore = "0.10, 1"
IntervalArithmetic = "0.17, 0.18, 0.19, 0.20, 0.21"
LinearAlgebra = "1.12.0"
NonconvexCore = "1.5"
NonconvexIpopt = "0.5"
Parameters = "0.12, 0.13"
Reexport = "1"
Sobol = "1"
julia = "1"

[extras]
NonconvexNLopt = "b43a31b8-ff9b-442d-8e31-c163daa8ab75"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["NonconvexNLopt", "Test", "Zygote"]
